### ISSUE TITLE
BUG: Endless Loop in running.

### ISSUE THREAD

**Issue by yhhu99** [baichen318/boom-explorer-public#2]
Hello, I found there is a bug that would cause endless loop in _intialize.py:177~188_. The _candidates_ got by TED may be duplicated in _x_, and would be removed in __delete_duplicate_ function. Therefore, the length of x will not be changed, and thus the loop is endless. This bug occurs randomly.

**Comment by baichen318** [comment]
Sorry for the late reply.
Thanks for pointing it out. I have made a bug fix for it: https://github.com/baichen318/boom-explorer-public/commit/0f3d6cbcdf5c9b506b1c87178345885a7014ede5.

Best regards,
Chen
