### ISSUE TITLE
The issue regarding the baseline for the Pareto curve.

### ISSUE THREAD

**Issue by zsjiang99** [baichen318/boom-explorer-public#4]
Hello, I would like to ask about the specific approach of obtaining baselines in this article. For example, how did random forest, XGBoost, and SVR obtain the Pareto curve, and what was their training set? Also, I would like to know if there are any relevant reference codes for these baselines.
![image](https://github.com/baichen318/boom-explorer-public/assets/97930258/816625f5-2ee5-43d0-b80b-cf4286e4e70c)

**Comment by baichen318** [comment]
Hi @luck-codeer ,

The baselines using random forest, XGBoost, and SVR are implemented with simulated annealing. One example can be found here: https://github.com/apache/tvm/blob/main/python/tvm/autotvm/tuner/sa_model_optimizer.py#L33.

The same design space is used for all baselines. You can check the example demonstration data set: https://github.com/baichen318/boom-explorer-public/blob/master/dataset/demo.csv.

Best regards,
Chen

**Comment by zsjiang99** [comment]
Thank you for your prompt reply@baichen318, but I still don't understand SA compares the single target object (such as the score below) when obtaining the next target point, and how it is used to obtain the Pareto curve (which has two targets). Can you please tell me how you solved this problem initially?
![image](https://github.com/baichen318/boom-explorer-public/assets/97930258/63640206-b160-443d-b53b-0be39359806f)

**Comment by baichen318** [comment]
Hi @luck-codeer ,

We use Pareto hypervolume as the object scalar value in simulated annealing. You can use other metrics. And searched solutions that are predicted to be Pareto optimal will be picked up.

Best regards,
Chen

**Comment by zsjiang99** [comment]
Hi @baichen318 ,  I apologize for the inconvenience, but I would like to confirm if it is correct to replace the model in the given code with corresponding traditional algorithm models such as Random Forest (RF), XGBoost, or Support Vector Regression (SVR), and then use the obtained Pareto hypervolume for simulated annealing prediction. However, I have found it difficult to combine the model, SA, and hypervolume using code, so I was wondering if you have any suggestions. Additionally, I would like to ask if you have any recommendations for quickly obtaining a corresponding baseline for your dataset.
![image](https://github.com/baichen318/boom-explorer-public/assets/97930258/690b75df-868d-4d58-93b7-5ced56f0c0bd)

**Comment by baichen318** [comment]
Hi @luck-codeer ,

It is inappropriate to replace the model in the code you provide (i.e., the computation of expectation improvement of Pareto Hypervolume) since the code requires the Gaussian process-like surrogate model to produce variance values.

In my implementation, I directly combine traditional models such as random forest (RF), XGBoost, and support vector regression (SVR) with simulated annealing. The prediction values are Pareto hypervolume instead of the expectation improvement of Pareto Hypervolume (EIPV). The computation of Pareto hypervolume only requires the searched objective values.

Best regards,
Chen

**Comment by zsjiang99** [comment]
Hi @baichen318 ,
I would like to understand how the calculation of the Pareto hypervolume for each point can be implemented through code. Is the following reference useful for this purpose?
![image](https://github.com/baichen318/boom-explorer-public/assets/97930258/234e284f-26e4-423b-b6bc-86e0cf58fc32)

**Comment by baichen318** [comment]
Hi @luck-codeer,

Regarding your implementation, some information is missing, like the computation of differences between predicted objective values and reference points. So, I cannot tell whether it is helpful for your purpose.

However, I will open source a general computation method in a different code repository shortly.

I will notify you of the example implementation once I release the codes to the public.

Best regards,
Chen

**Comment by zsjiang99** [comment]
Thanks a lot for your help! @baichen318 .

**Comment by baichen318** [comment]
> Thanks a lot for your help! @baichen318 .

Hi @luck-codeer ,

Please refer to https://github.com/iccad-contest/iccad-contest-platform/blob/master/iccad_contest/functions/hypervolume.py#L24 for the Pareto hypervolume computation implementation.

In the implementation, we assume minimization is performed for the problem.
