### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)

### ISSUE THREAD

**Issue by zhy679** [baichen318/boom-explorer-public#5]
您好，我在跑代码的时候遇到了这个问题，想知道如何解决比较好
<img width="570" alt="截屏2024-01-10 22 00 22" src="https://github.com/baichen318/boom-explorer-public/assets/104006829/d1fce4d9-3333-4e74-8786-9f03bebcb0b4">

**Comment by baichen318** [comment]
Hi @zhy679 ,

The released codes are only supported to run on CPUs instead of the GPU. You need to revise codes to ensure that every tensor is on the same device when you compute results with DKL-GP.

Best regards,
Chen

**Comment by zhy679** [comment]
好的，谢谢您。不过源码里关于DKL-GP这一部分，self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")优先用的cuda，只能在cpu上跑那么此处是否可以做些修改呢，一点愚见，希望您能给我解惑。
